name = "ComplementaritySolve"
uuid = "b40a91a3-bdaf-4e1c-b965-8c278a33a8d3"
authors = ["Avik Pal <avikpal@mit.edu>"]
version = "0.1.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
